// Copyright (C) 2023 Korea Association of AI Smart Home.
// Licensed under the Apache License, Version 2.0
// Auto-generated by designer

namespace SmartHomeEmulator.UI
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        // ---- Controls ----
        private System.Windows.Forms.Label     lblPort;
        private System.Windows.Forms.ComboBox  comboPort;
        private System.Windows.Forms.Button    btnRefreshPorts;
        private System.Windows.Forms.Label     lblBaudrate;
        private System.Windows.Forms.ComboBox  comboBaudrate;
        private System.Windows.Forms.Label     lblProtocol;
        private System.Windows.Forms.ComboBox  comboProtocol;
        private System.Windows.Forms.Label     lblMode;
        private System.Windows.Forms.ComboBox  comboMode;
        private System.Windows.Forms.Button    btnStart;
        private System.Windows.Forms.Button    btnStop;
        private System.Windows.Forms.Label     lblStatusLabel;
        private System.Windows.Forms.Label     lblStatus;
        private System.Windows.Forms.GroupBox  grpDevices;
        private System.Windows.Forms.ListView  listDevices;
        private System.Windows.Forms.Label     lblDeviceDetail;
        private System.Windows.Forms.GroupBox  grpLog;
        private System.Windows.Forms.RichTextBox txtLog;
        private System.Windows.Forms.Button    btnClearLog;
        private System.Windows.Forms.SplitContainer splitMain;
        private System.Windows.Forms.Panel     panelTop;

        private void InitializeComponent()
        {
            this.components     = new System.ComponentModel.Container();

            // ---- Top panel controls ----
            this.lblPort        = new System.Windows.Forms.Label();
            this.comboPort      = new System.Windows.Forms.ComboBox();
            this.btnRefreshPorts= new System.Windows.Forms.Button();
            this.lblBaudrate    = new System.Windows.Forms.Label();
            this.comboBaudrate  = new System.Windows.Forms.ComboBox();
            this.lblProtocol    = new System.Windows.Forms.Label();
            this.comboProtocol  = new System.Windows.Forms.ComboBox();
            this.lblMode        = new System.Windows.Forms.Label();
            this.comboMode      = new System.Windows.Forms.ComboBox();
            this.btnStart       = new System.Windows.Forms.Button();
            this.btnStop        = new System.Windows.Forms.Button();
            this.lblStatusLabel = new System.Windows.Forms.Label();
            this.lblStatus      = new System.Windows.Forms.Label();
            this.panelTop       = new System.Windows.Forms.Panel();

            // ---- Body controls ----
            this.splitMain      = new System.Windows.Forms.SplitContainer();
            this.grpDevices     = new System.Windows.Forms.GroupBox();
            this.listDevices    = new System.Windows.Forms.ListView();
            this.lblDeviceDetail= new System.Windows.Forms.Label();
            this.grpLog         = new System.Windows.Forms.GroupBox();
            this.txtLog         = new System.Windows.Forms.RichTextBox();
            this.btnClearLog    = new System.Windows.Forms.Button();

            this.SuspendLayout();

            // ==== Top Panel ====
            this.panelTop.Dock    = System.Windows.Forms.DockStyle.Top;
            this.panelTop.Height  = 110;
            this.panelTop.Padding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.panelTop.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;

            // COM Port row
            this.lblPort.Text = "COM Port:";
            this.lblPort.AutoSize = true;
            this.lblPort.Location = new System.Drawing.Point(8, 10);

            this.comboPort.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboPort.Width  = 120;
            this.comboPort.Location = new System.Drawing.Point(80, 7);

            this.btnRefreshPorts.Text = "↺ Refresh";
            this.btnRefreshPorts.Width  = 75;
            this.btnRefreshPorts.Height = 23;
            this.btnRefreshPorts.Location = new System.Drawing.Point(208, 7);
            this.btnRefreshPorts.Click += new System.EventHandler(this.btnRefreshPorts_Click);

            // Baud rate row
            this.lblBaudrate.Text = "Baudrate:";
            this.lblBaudrate.AutoSize = true;
            this.lblBaudrate.Location = new System.Drawing.Point(8, 40);

            this.comboBaudrate.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBaudrate.Width  = 100;
            this.comboBaudrate.Location = new System.Drawing.Point(80, 37);

            // Protocol row
            this.lblProtocol.Text = "Protocol:";
            this.lblProtocol.AutoSize = true;
            this.lblProtocol.Location = new System.Drawing.Point(300, 10);

            this.comboProtocol.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboProtocol.Width  = 160;
            this.comboProtocol.Location = new System.Drawing.Point(370, 7);

            // Mode row
            this.lblMode.Text = "Mode:";
            this.lblMode.AutoSize = true;
            this.lblMode.Location = new System.Drawing.Point(300, 40);

            this.comboMode.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboMode.Width  = 160;
            this.comboMode.Location = new System.Drawing.Point(370, 37);

            // Start / Stop buttons
            this.btnStart.Text     = "▶ Start";
            this.btnStart.Width    = 90;
            this.btnStart.Height   = 30;
            this.btnStart.Location = new System.Drawing.Point(560, 10);
            this.btnStart.BackColor= System.Drawing.Color.LightGreen;
            this.btnStart.Click   += new System.EventHandler(this.btnStart_Click);

            this.btnStop.Text      = "■ Stop";
            this.btnStop.Width     = 90;
            this.btnStop.Height    = 30;
            this.btnStop.Location  = new System.Drawing.Point(660, 10);
            this.btnStop.BackColor = System.Drawing.Color.LightCoral;
            this.btnStop.Enabled   = false;
            this.btnStop.Click    += new System.EventHandler(this.btnStop_Click);

            // Status
            this.lblStatusLabel.Text     = "Status:";
            this.lblStatusLabel.AutoSize = true;
            this.lblStatusLabel.Location = new System.Drawing.Point(560, 52);

            this.lblStatus.Text      = "○ STOPPED";
            this.lblStatus.AutoSize  = true;
            this.lblStatus.ForeColor = System.Drawing.Color.Gray;
            this.lblStatus.Font      = new System.Drawing.Font("Segoe UI", 10, System.Drawing.FontStyle.Bold);
            this.lblStatus.Location  = new System.Drawing.Point(620, 50);

            this.panelTop.Controls.AddRange(new System.Windows.Forms.Control[]
            {
                lblPort, comboPort, btnRefreshPorts,
                lblBaudrate, comboBaudrate,
                lblProtocol, comboProtocol,
                lblMode, comboMode,
                btnStart, btnStop,
                lblStatusLabel, lblStatus,
            });

            // ==== Split Container ====
            ((System.ComponentModel.ISupportInitialize)(this.splitMain)).BeginInit();
            this.splitMain.Panel1.SuspendLayout();
            this.splitMain.Panel2.SuspendLayout();

            this.splitMain.Dock        = System.Windows.Forms.DockStyle.Fill;
            this.splitMain.Orientation = System.Windows.Forms.Orientation.Vertical;
            this.splitMain.SplitterDistance = 300;

            // ---- Left: Device list ----
            this.grpDevices.Text  = "Devices";
            this.grpDevices.Dock  = System.Windows.Forms.DockStyle.Fill;

            this.listDevices.Dock = System.Windows.Forms.DockStyle.Top;
            this.listDevices.Height = 230;
            this.listDevices.View  = System.Windows.Forms.View.Details;
            this.listDevices.FullRowSelect = true;
            this.listDevices.GridLines     = true;
            this.listDevices.Columns.Add("Name",    160);
            this.listDevices.Columns.Add("Address",  80);
            this.listDevices.Columns.Add("State",    60);
            this.listDevices.Columns.Add("Status",   80);
            this.listDevices.SelectedIndexChanged += new System.EventHandler(this.listDevices_SelectedIndexChanged);

            this.lblDeviceDetail.Dock      = System.Windows.Forms.DockStyle.Fill;
            this.lblDeviceDetail.Text      = "";
            this.lblDeviceDetail.Font      = new System.Drawing.Font("Consolas", 9);
            this.lblDeviceDetail.TextAlign = System.Drawing.ContentAlignment.TopLeft;
            this.lblDeviceDetail.Padding   = new System.Windows.Forms.Padding(6);
            this.lblDeviceDetail.BorderStyle = System.Windows.Forms.BorderStyle.None;

            this.grpDevices.Controls.Add(this.lblDeviceDetail);
            this.grpDevices.Controls.Add(this.listDevices);
            this.splitMain.Panel1.Controls.Add(this.grpDevices);

            // ---- Right: Log ----
            this.grpLog.Text  = "Log";
            this.grpLog.Dock  = System.Windows.Forms.DockStyle.Fill;

            this.btnClearLog.Text    = "Clear";
            this.btnClearLog.Dock    = System.Windows.Forms.DockStyle.Bottom;
            this.btnClearLog.Height  = 24;
            this.btnClearLog.Click  += new System.EventHandler(this.btnClearLog_Click);

            this.txtLog.Dock       = System.Windows.Forms.DockStyle.Fill;
            this.txtLog.ReadOnly   = true;
            this.txtLog.Font       = new System.Drawing.Font("Consolas", 8.5f);
            this.txtLog.ScrollBars = System.Windows.Forms.RichTextBoxScrollBars.Vertical;
            this.txtLog.WordWrap   = false;

            this.grpLog.Controls.Add(this.txtLog);
            this.grpLog.Controls.Add(this.btnClearLog);
            this.splitMain.Panel2.Controls.Add(this.grpLog);

            ((System.ComponentModel.ISupportInitialize)(this.splitMain)).EndInit();
            this.splitMain.Panel1.ResumeLayout(false);
            this.splitMain.Panel2.ResumeLayout(false);

            // ==== Form ====
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode       = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize          = new System.Drawing.Size(900, 600);
            this.Controls.Add(this.splitMain);
            this.Controls.Add(this.panelTop);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
            this.FormClosing    += new System.Windows.Forms.FormClosingEventHandler(this.MainForm_FormClosing);
            this.StartPosition   = System.Windows.Forms.FormStartPosition.CenterScreen;

            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
